FROM archlinux:base

ENV container=docker

# Initialize and update keyring before running a full system upgrade
RUN pacman-key --init && \
    pacman-key --populate archlinux && \
    pacman -Sy --noconfirm archlinux-keyring && \
    pacman -Syu --noconfirm

# Install required packages
RUN pacman -S --noconfirm --needed \
    act \
    bats-assert bats-file bats-support \
    nodejs npm \
    kcov \
    git \
    lvm2 \
    btrfs-progs \
    parallel

RUN pacman -Scc --noconfirm

# Prepare for systemd boot
STOPSIGNAL SIGRTMIN+3

VOLUME [ "/sys/fs/cgroup" ]

# This ensures journald doesn't hang waiting for tty
RUN sed -i 's/#LogLevel=info/LogLevel=debug/' /etc/systemd/journald.conf

# Mask services that are known to fail in Docker
RUN systemctl mask \
    systemd-firstboot.service \
    systemd-udevd \
    systemd-udev-trigger \
    systemd-journald-audit.socket \
    getty@.service \
    console-getty.service \
    systemd-remount-fs.service \
    systemd-sysctl.service \
    systemd-tmpfiles-setup.service \
    systemd-tmpfiles-clean.timer

CMD ["/usr/lib/systemd/systemd"]
