---
# Filename: .github/workflows/test_test_environment.yaml
name: Test Test Environment Workflow
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:  # usage: gh workflow run <workflow_name> --ref <branch_name>
jobs:
  test-bats-common-setup:
    runs-on: ubuntu-latest
    container:
      image: robertportelli/readiluks-inner-harness:latest
      options: --user root
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Run BATS Tests
        run: bats test/unit/test_common_setup.bats
