---
# Filename: .github/workflows/test_parser.yaml
# Manual usage:
#  # with defaults:
#    # gh workflow run test-parser
#  # override defaults:
#    # gh workflow run test-parser --input bats-flags="--timing"
#  # run without bats flags
#    # gh workflow run test-parser --input bats-flags=""
name: Test Production Parser
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      bats-flags:
        description: "Flags to pass to BATS"
        required: false
        default: "--verbose-run --show-output-of-passing-tests --timing"
jobs:
  test-parser:
    runs-on: ubuntu-latest
    container:
      image: robertportelli/test-readiluks:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Production Argument Parser BATS Tests
        env:
          BATS_FLAGS: ${{ github.event.inputs.bats-flags }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |-
          echo "BATS_FLAGS value: '${BATS_FLAGS}'"
          echo "GITHUB_EVENT_NAME: '${GITHUB_EVENT_NAME}'"

          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "PR Trigger detected: Using default CI bats-flags: --tap"
            bats --tap test/unit/test_parser.bats
          elif [[ "${{ github.event.inputs.bats-flags }}" == "" ]]; then
            echo "Manual Trigger detected: Running BATS with no flags"
            bats test/unit/test_parser.bats
          elif [[ -z "$BATS_FLAGS" ]]; then
            echo "Manual Trigger detected: Running BATS with default flags"
            bats --verbose-run --show-output-of-passing-tests --timing test/unit/test_parser.bats
          else
            echo "Manual Trigger detected: Running BATS with bats-flags: $BATS_FLAGS"
            bats "$BATS_FLAGS" test/unit/test_parser.bats
          fi
